routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//No need now
//Auth::routes();
//Route::get('/home', 'HomeController@index')->name('home');


Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => '', 'uses' => 'Auth\LoginController@login']);
Route::get('/admin_cms', 'HomeController@index');
Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);



Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::group(['prefix' => '/admin_cms', 'middleware' => ['auth']], function () {

    Route::get('/', function () {
        return view('admin.core');
    });

    Route::resource('page', 'PageController');

    Route::resource('image', 'GalleryController');


    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

    Route::group(['prefix' => 'category'], function () {
        Route::get('/', 'CategoryController@index')->name('category.index');
        Route::get('/create', 'CategoryController@create')->name('category.create');
        Route::post('/create', 'CategoryController@store');

        Route::group(['prefix' => '{id}'], function () {
            Route::get('/edit', 'CategoryController@edit')->name('category.edit');
            Route::post('/edit', 'CategoryController@update');
            Route::delete('/delete', 'CategoryController@destroy')->name('category.delete');

        });
    });
    Route::resource('subcategory', 'SubCategoryController');
});

resources/views/admin/page/create.blade.php
@extends('admin.core')

@section('content')
    <div class="row">
        <h4>Create page</h4>
        <form class="col s12" action="{{ route('page.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="row">
                <div class="input-field col s12 m6">
                    <select name="category">
                        <option value="1">Category 1</option>
                    </select>
                    <label>Category</label>
                </div>
                <div class="input-field col s12 m6">
                    <select name="subcategory">
                        <option value="" disabled selected>Choose page subcategory</option>
                        <option value="1">SubCategory 1</option>
                        <option value="1">SubCategory 2</option>
                    </select>
                    <label>Sub Category</label>
                </div>
                <div class="input-field col s12 m6">
                    <select name="position">
                        <option value="1">Position 1</option>
                    </select>
                    <label>Position</label>
                </div>
                <div class="input-field col s12 m6">
                    <select icons name="image[]" id="image" multiple>
                        <option value="" disabled selected>Choose images</option>
                        @foreach($galleries as $cover)
                            <option value="{{$cover->path}}" data-icon="{{$cover->path}}" class="left circle"></option>
                        @endforeach
                    </select>
                    <label>Choose image</label>
                </div>
                <div class="input-field col s12">
                    <input name="title" id="title" type="text" class="validate">
                    <label for="title">Title</label>
                </div>
                <div class="input-field col s12">
                    <label>Textarea</label>
                    <br>
                    <br>
                    <textarea name="description"></textarea>
                </div>
            </div>
            <button class="btn waves-effect waves-light" type="submit">Save Page</button>
        </form>
        @include('mceImageUpload::upload_form')
    </div>

@endsection

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="/js/tinymce/js/tinymce.min.js"></script>
<script src="/js/tinymce.js"></script>

resources/views/admin/page/edit.blade.php
@extends('admin.core')

@section('content')
    <div class="row">
        <h4>Edit page {{$page->title}}</h4>
        <form class="col s12" action="{{ route('page.update', ['id' => $page->id]) }}" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="input-field col s12 m6">
                    <select>
                        <option value="1">Category 1</option>
                    </select>
                    <label>Category</label>
                </div>
                <div class="input-field col s12 m6">
                    <select>
                        <option value="" disabled selected>Choose page subcategory</option>
                        <option value="1">SubCategory 1</option>
                    </select>
                    <label>Sub Category</label>
                </div>
                <div class="input-field col s12 m6">
                    <select>
                        <option value="1">Position 1</option>
                    </select>
                    <label>Position</label>
                </div>
                <div class="input-field col s12 m6">
                    <select>
                        <option value="" disabled selected>Choose page image</option>
                        <option value="1">Cover image</option>
                    </select>
                    <label>Cover image</label>
                </div>
                <div class="input-field col s12">
                    <input id="title" type="text" class="validate">
                    <label for="title">Title</label>
                </div>
                <div class="input-field col s12">
                    <label>Textarea</label>
                    <br>
                    <br>
                    <textarea></textarea>
                </div>
            </div>
            <button class="btn waves-effect waves-light" type="submit" name="action">Save Page</button>
        </form>
        @include('mceImageUpload::upload_form')
    </div>

@endsection

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="/js/tinymce/js/tinymce.min.js"></script>
<script src="/js/tinymce.js"></script>

resources/views/admin/page/index.blade.php
@extends('admin.core')


@section('content')
<div class="row">
    <h2>All pages</h2>
    <a class="waves-effect waves-light btn" href="{{route('page.create')}}">New page</a>
</div>
<div class="row">
    @foreach($pages as $key => $page)
    <div class="col s12 m6">
        <div class="card small">
            <div class="card-image waves-effect waves-block waves-light">
                <img class="activator" id="title_cover" src="/images/no-image.jpg"> {{--must be {{$page->cover}}--}}
            </div>
            <div class="card-content">
                <span class="card-title activator grey-text text-darken-4">{{$page->title}}<i class="material-icons right">more_vert</i></span>
                <p><a href="{{route('page.edit', $page->id)}}" class="waves-effect waves-light btn">Edit</a>
                {{--<a href="{{route('page.destroy', $page->id)}}" class="waves-effect waves-light btn">Delete</a>--}}

                    <button onclick="deleteAll('{{route('page.destroy', $page->id)}}')" class="waves-effect waves-light btn">Delete</button>


                <a class="waves-effect waves-light btn">Off</a></p> {{--must be {{$page->visible}}--}}
            </div>
            <div class="card-reveal">
                <span class="card-title grey-text text-darken-4">{{$page->title}}<i class="material-icons right">close</i></span>
                <p>Category: {{$page->category_id}}</p>
                <p>{{substr(strip_tags($page->description),0, 500)}}{{ strlen(strip_tags($page->description)) > 500 ? '...' : "" }}
                    <a href="{{route('page.show', $page->id)}}">...more</a></p>
                <p>Position: {{$page->position}}</p>
                <p>Create: {{$page->created_at->format('Y-m-d')}}</p>
            </div>
        </div>
    </div>
    @endforeach
</div>
@endsection

resources/views/admin/page/show.blade.php
@extends('admin.core')


@section('content')
    <div class="row">
        <div class="col s12 m10 offset-m1">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" id="title_cover" src="/images/no-image.jpg"> {{--must be {{$page->cover}}--}}
                </div>
                <div class="card-panel">
                    <h4>Title: {{$page->title}}</h4>
                    <p>Category: {{$page->category_id}}</p>
                    <p>{{$page->description}}</p>
                    <p>Position: {{$page->position}}</p>
                    <p>Slug: {{$page->slug}}</p>
                    <p>Create: {{$page->created_at->format('Y-m-d')}}</p>
                    <p>
                        <a href="{{route('page.edit', $page->id)}}" class="waves-effect waves-light btn">Edit</a>
                        <a class="waves-effect waves-light btn">Off</a>{{-- must be {{$page->visible}}--}}
                        <a class="waves-effect waves-light btn" href="{{route('page.index')}}">Back</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection