routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//No need now
//Auth::routes();
//Route::get('/home', 'HomeController@index')->name('home');


Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => '', 'uses' => 'Auth\LoginController@login']);
Route::get('/admin_cms', 'HomeController@index');
Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);



Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::group(['prefix' => '/admin_cms', 'middleware' => ['auth']], function () {

    Route::get('/', function () {
        return view('admin.core');
    });

    Route::resource('page', 'PageController');

    Route::resource('image', 'GalleryController');


    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

    Route::group(['prefix' => 'category'], function () {
        Route::get('/', 'CategoryController@index')->name('category.index');
        Route::get('/create', 'CategoryController@create')->name('category.create');
        Route::post('/create', 'CategoryController@store');

        Route::group(['prefix' => '{id}'], function () {
            Route::get('/edit', 'CategoryController@edit')->name('category.edit');
            Route::post('/edit', 'CategoryController@update');
            Route::delete('/delete', 'CategoryController@destroy')->name('category.delete');

        });
    });
    Route::resource('subcategory', 'SubCategoryController');
});

app/SubCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'position','category_id',
    ];
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\SubCategory;
use Illuminate\Http\Request;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list = SubCategory::get();
        return view('admin.subcategory.index')->with('list', $list);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::get()->pluck('name','id');
        return view('admin.subcategory.create')->with('category',$category);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        Subcategory::create([
            'name' => $request->name,
            'position' => $request->position,
            'category_id' => $request->category_id,

        ]);
        return redirect()->route('subcategory.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function show(SubCategory $subCategory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function edit(SubCategory $subCategory, $id)
    {

        $category = Category::get()->pluck('name','id');
        return view('admin.subcategory.edit')->with(['subCategory'=>$subCategory->find($id), 'category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SubCategory $subCategory, $id)
    {
        $subCategory->find($id)->update($request->toArray());
        return redirect()->route('subcategory.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(SubCategory $subCategory, $id)
    {
        $subCategory->destroy($id);

        return ["success" => true, "id" => $id];
    }
}

resources/views/admin/subcategory/create.blade.php
@extends('admin.core')

@section('content')

    <div class="row">


        {!! Form::open(['url' =>  route('subcategory.store'), 'method' => 'post', 'class'=>'col s12'])!!}

        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="row">
            <div class="input-field col s6">

                {{Form::label('name', 'SubCategory name')}}
                {{Form::text('name', null)}}

            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">

                {{Form::label('position', 'Enter subcategory position')}}
                {{Form::text('position', null)}}

            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">


                {{Form::select('category_id',$category , null, ['placeholder' => 'Pick a category id...'])}}
            </div>
        </div>


        {{Form::submit('Submit', array('class' => 'btn waves-effect waves-light')) }}

        {!! Form::close() !!}
    </div>










@endsection

resources/views/admin/subcategory/edit.blade.php
@extends('admin.core')

@section('content')

    <div class="row">


        {!! Form::open(['url' =>  route('subcategory.update',['id'=>$subCategory->id]), 'method' => 'POST', 'class'=>'col s12'])!!}
        <input type="hidden" name="_method" value="PUT">

        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="row">
            <div class="input-field col s6">

                {{Form::label('name', 'Category name')}}
                {{Form::text('name', $subCategory->name)}}

            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">

                {{Form::label('position', 'Enter subcategory position')}}
                {{Form::text('position', $subCategory->position)}}

            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">


                {{Form::select('category_id',$category , $subCategory->position)}}
            </div>
        </div>


        {{Form::submit('Submit', array('class' => 'btn waves-effect waves-light')) }}

        {!! Form::close() !!}
    </div>










@endsection

resources/views/admin/subcategory/index.blade.php
@extends('admin.core')

@section('content')
    <h2>Category table</h2>

    <a href="{{route('subcategory.create')}}">
        <button type="button" class="waves-effect waves-light yellow btn">New category</button>
    </a>

    <table class="striped">
        <thead>
        <tr>
            <th>id</th>
            <th>position</th>
            <th>name</th>
            <th>category id</th>
        </tr>
        </thead>

        <tbody>

        @foreach ($list as $key => $value)
            <tr id="{{$value->id}}">
                <td>{{$value->id}}</td>
                <td>{{$value->position}}</td>
                <td>{{$value->name}}</td>
                <td>{{$value->category_id}}</td>

                <td>
                    <a href="{{route('subcategory.edit',$value->id)}}">
                        <button type="button" class="waves-effect waves-light btn">Edit</button>
                    </a>
                </td>

                <td>
                    <a>
                        <button type="button" class="waves-effect  waves-light red btn"
                                onclick="deleteAll('{{route('subcategory.destroy',$value->id)}}')">Delete
                        </button>
                    </a>
                </td>


                @endforeach
            </tr>
        </tbody>
    </table>
@endsection