routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//No need now
//Auth::routes();
//Route::get('/home', 'HomeController@index')->name('home');


Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => '', 'uses' => 'Auth\LoginController@login']);
Route::get('/admin_cms', 'HomeController@index');
Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);



Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::group(['prefix' => '/admin_cms', 'middleware' => ['auth']], function () {

    Route::get('/', function () {
        return view('admin.core');
    });

    Route::resource('page', 'PageController');

    Route::resource('image', 'GalleryController');


    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

    Route::group(['prefix' => 'category'], function () {
        Route::get('/', 'CategoryController@index')->name('category.index');
        Route::get('/create', 'CategoryController@create')->name('category.create');
        Route::post('/create', 'CategoryController@store');

        Route::group(['prefix' => '{id}'], function () {
            Route::get('/edit', 'CategoryController@edit')->name('category.edit');
            Route::post('/edit', 'CategoryController@update');
            Route::delete('/delete', 'CategoryController@destroy')->name('category.delete');

        });
    });
    Route::resource('subcategory', 'SubCategoryController');
});

resources/views/admin/core.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>CMS-Laravel</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <link href="{{ URL::asset('css/admin_panel.css') }}" type="text/css" rel="stylesheet" media="screen,projection"/>

</head>
<body>

@include('admin.navbar')
<div class="row">

    @include('admin.sidbar')

    <div class="col s12 m8 l9"> <!-- Note that "m8 l9" was added -->
        @yield('content')

    </div>

    <div class="col s12 m8 l9"> <!-- Note that "m8 l9" was added -->

        Tables
        <!-- Teal page content


              This content will be:
          9-columns-wide on large screens,
          8-columns-wide on medium screens,
          12-columns-wide on small screens  -->
    </div>

</div>


<!--  Scripts-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script src="/js/admin_panel.js"></script>





</body>


</html>

resources/views/admin/navbar.blade.php
<nav class="light-blue grey darken-3" role="navigation">
    <div class="nav-wrapper">
        <ul class="right hide-on-med-and-down">
            <li><a href="/admin_cms"><span class="material-icons">face</span>Admin</a></li>
            <li><a title="View Website" href="/"><span class="material-icons">language</span>Web</a></li>
            <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    <span class="material-icons">exit_to_app</span>
                    Logout</a></li>
            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                  style="display: none;">{{ csrf_field() }}
            </form>
        </ul>

        <ul id="nav-mobile" class="side-nav">
            <li><a href="/admin_cms"><span class="material-icons">face</span>Admin</a></li>
            <li><a title="View Website" href="/"><span class="material-icons">language</span>Web</a></li>
            <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    <span class="material-icons">exit_to_app</span>Logout</a></li>
            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                  style="display: none;">{{ csrf_field() }}
            </form>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
</nav>

resources/views/admin/sidbar.blade.php
<div class="col s12 m2 darken-3 sidbar"><!-- Note that "m4 l3" was added -->
    <a href="#" ><h5 class="link">Dashboard</h5></a>
    <a href="{{route('page.index')}}" ><h5 class="link">Pages</h5></a>
    <a href="{{route('category.index')}}" ><h5 class="link">Categories</h5></a>
    <a href="{{route('subcategory.index')}}" ><h5 class="link">SubCategories</h5></a>
    <a href="{{route('image.index')}}" ><h5 class="link">Galleries</h5></a>

</div>